# Generated by Django 5.1.4 on 2024-12-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='randomMadal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('famous_saying', models.CharField(max_length=1000)),
                ('complite', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Random',
                'verbose_name_plural': 'Randoms',
                'db_table': 'Random',
            },
        ),
    ]
